#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_w

# my self test
param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MODE 0
param set-default SDLOG_PROFILE 19
param set-default RTL_RETURN_ALT 3.0
# my self test end
